# Generated by Django 6.1 on 2026-08-24 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField()),
                ('organizer', models.CharField(max_length=20)),
                ('venue', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/events/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CANCELLED', 'Cancelled'), ('PUBLISHED', 'Published'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tickets.category')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('REGULAR', 'Regular'), ('VIP', 'VIP'), ('VVIP', 'VVIP')], default='regular')),
                ('price', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.event')),
            ],
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='end_date_after_start_date'),
        ),
    ]
