# Generated by Django 6.1 on 2026-09-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='transaction_uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
