# Generated by Django 6.1 on 2026-09-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_booking_transaction_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='khalti_pidx',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('ESEWA', 'Esewa'), ('KHALTI', 'Khalti')], default='ESEWA', max_length=20),
        ),
    ]
