# Generated by Django 6.1 on 2026-09-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_booking_khalti_pidx_booking_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('ESEWA', 'Esewa'), ('KHALTI', 'Khalti')], max_length=20),
        ),
    ]
