# Generated by Django 6.1 on 2026-09-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_contactmessage'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('event', 'ticket_type'), name='unique_ticket_type_per_event'),
        ),
    ]
