# Generated by Django 6.1 on 2026-09-29 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_artist_description_venue_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.IntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tickets.booking')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.ticket')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('booking', 'ticket'), name='unique_ticket_per_booking')],
            },
        ),
    ]
