# Generated by Django 6.1 on 2026-10-01 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_promocode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='valid_form',
            new_name='valid_from',
        ),
    ]
