# Generated by Django 6.1 on 2026-10-01 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_rename_valid_form_promocode_valid_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='promocode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.promocode'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='applicable_events',
            field=models.ManyToManyField(blank=True, to='tickets.event'),
        ),
    ]
