# Generated by Django 6.1 on 2026-10-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_booking_promocode_promocode_applicable_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.IntegerField(null=True),
        ),
    ]
