# Generated by Django 6.1 on 2026-10-01 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_booking_discount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='is_used',
        ),
    ]
