# Generated by Django 6.1 on 2026-10-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_remove_promocode_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='valid_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_to',
            field=models.DateField(),
        ),
    ]
